% startup.m
% Called at MATLAB startup.
% Sets defaults for figures (use 0 for figure handle)

% Adjust figure defaults for better font read-ability
set(0,'DefaultFigureColor',     'white',...
      'DefaultAxesColor',       'white',...
      'DefaultTextFontSize',    16,...
      'DefaultAxesFontSize',    14,...
      'DefaultTextFontWeight',  'bold',...
      'DefaultAxesFontWeight',  'bold');

  
% % Enable this section for black-background figures
% set(0,'DefaultFigureColor',     'black',...
%     'DefaultAxesColor',       'black',...
%     'DefaultTextColor',     [1,1,1],...
%     'DefaultAxesXcolor',    [1,1,1],...
%     'DefaultAxesYcolor',    [1,1,1],...
%     'DefaultAxesZcolor',    [1,1,1]);

% Converting back from black-background
set(0,'DefaultFigureColor',     'white',...
    'DefaultAxesColor',       'white',...
    'DefaultTextColor',     [0,0,0],...
    'DefaultAxesXcolor',    [0,0,0],...
    'DefaultAxesYcolor',    [0,0,0],...
    'DefaultAxesZcolor',    [0,0,0]);

% Load up my lovely custom colormap that uses black as middle value.
% load('MyColormaps');
% set(0,'DefaultFigureColormap',mycmap);

clear;

